spring:
  data:
  mongodb:
    username: michael
    password: michael
    host: localhost
    port: 27017
    database: notification
    authentication-database: admin


  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.michael.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.michael.ecommerce.notification.PaymentNotificationRequest


  mail:
    host: localhost
    port: 1025
    username: michael
    password: michael
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
          connection-timeout: 5000
          timeout: 3000
          write-timeout: 5000
logging:
  level:
    org:
      apache:
        kafka=DEBUG:
server:
  port: 8040